version: '3.8'

services:
  email-sending-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=465
      - MAIL_SECURE=true
      - MAIL_USER=7daa946e9c9bf6
      - MAIL_PASS=e0fd75d6984bee
      - MAIL_FROM=test@example.com
      - PORT=3000

  email-sending-test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "test"]
    environment:
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=465
      - MAIL_SECURE=true
      - MAIL_USER=7daa946e9c9bf6
      - MAIL_PASS=e0fd75d6984bee
      - MAIL_FROM=test@example.com
      - PORT=3000

